CREATE DATABASE IF NOT EXISTS db_users;

USE db_users;

CREATE TABLE TB_USERS(
  USE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USE_EMAIL VARCHAR(255) NOT NULL,
  USE_PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO TB_USERS(USE_EMAIL, USE_PASSWORD) 
VALUES('johndoe@gmail.com', '123456');